{
 "title": "Qwilt Observability",
 "time": { "from": "2025-03-27T00:02:00.000Z", "to": "2025-03-27T00:05:59.000Z" },
 "templating": {
  "list": [
   { "name": "table", "query": "integrations.qwilt" },
   {
    "name": "catalog",
    "query": "SELECT concat(project,'.`',table,'#.catalog`')\nFROM (SELECT splitByChar('.','${table}')[1] as project, splitByChar('.','${table}')[2] as table)"
   },
   { "name": "filter" },
   { "name": "timefilter", "query": "timestamp" }
  ]
 },
 "panels": [
  {
   "title": "Hits per status code",
   "type": "timeseries",
   "description": "Number of request group by HTTP Status Code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT toString(response_status_code) as HTTP_Status_Code, $__timeInterval(timestamp) as time, count(*) as http\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nGROUP BY HTTP_Status_Code, time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Hits per status code; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "Cache Hit Ratio :\nsum of all request with cache_was_cached: 1 / divided by total count of request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, cache_hit FROM(\nSELECT $__timeInterval(timestamp) as time,\nsumIf(cache_was_cached,1) as \"cached\",\ncached/count() * 100 as \"cache_hit\"\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nGROUP BY time ORDER BY time)\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Cache Hit Ratio; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Throughput is the sum of all bytes delivered / divided by sum of transfer time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time,\nsum(response_total_bytes) / sum(response_time_to_last_byte_ms/1000) as throughput\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Throughput; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "timeseries",
   "description": "Sum of Total Bytes Delivered",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time,\nsum(response_total_bytes) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bytes Delivered; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 Path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(request_full_path)\n        FROM ${table}\n        WHERE $__timeFilter(timestamp)\n            AND $__adHocFilter() \n) AS top_50_request_full_path\nSELECT\n    count(),\n    request_full_path\nFROM ${table}\nWHERE $__timeFilter(timestamp) AND has(top_50_request_full_path, request_full_path)\nAND $__adHocFilter()\nGROUP BY request_full_path\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 Path; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 User Agent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(request_user_agent)\n        FROM ${table}\n        WHERE $__timeFilter(timestamp)\n            AND $__adHocFilter() \n) AS top_50_request_user_agent\nSELECT\n    count(),\n    request_user_agent\nFROM ${table}\nWHERE $__timeFilter(timestamp) AND has(top_50_request_user_agent, request_user_agent)\nAND $__adHocFilter()\nGROUP BY request_user_agent\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 User Agent; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Request Per Content Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ncount(),\nresponse_content_type\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND response_content_type IS not NULL\nAND $__adHocFilter()\nGROUP BY response_content_type ORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Request Per Content Type; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(client_ip)\n        FROM ${table}\n        WHERE $__timeFilter(timestamp)\n            AND $__adHocFilter() \n) AS top_50_client_ip\nSELECT\n    count(),\n    client_ip\nFROM ${table}\nWHERE $__timeFilter(timestamp) AND has(top_50_client_ip, client_ip)\nAND $__adHocFilter()\nGROUP BY client_ip\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 IP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Edge TransferTime",
   "type": "timeseries",
   "description": "The time in milliseconds from when the edge server is ready to send the first byte of the response to when the last byte reaches the kernel.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time,\nquantile(0.25)(response_time_to_last_byte_ms) as 25th,\nquantile(0.5)(response_time_to_last_byte_ms) as 50th,\nquantile(0.75)(response_time_to_last_byte_ms) as 75th,\nquantile(0.9)(response_time_to_last_byte_ms) as 90th,\nquantile(0.95)(response_time_to_last_byte_ms) as 95th,\nquantile(0.99)(response_time_to_last_byte_ms) as 99th\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Edge TransferTime; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Edge Turn Around Time",
   "type": "timeseries",
   "description": "The time in milliseconds from when the edge server receives the last byte of the request to when it sends the first bytes of the response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time,\nquantile(0.25)(response_time_to_last_byte_ms) as 25th,\nquantile(0.5)(response_time_to_first_byte_ms) as 50th,\nquantile(0.75)(response_time_to_first_byte_ms) as 75th,\nquantile(0.9)(response_time_to_first_byte_ms) as 90th,\nquantile(0.95)(response_time_to_first_byte_ms) as 95th,\nquantile(0.99)(response_time_to_first_byte_ms) as 99th\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Edge Turn Around Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "rawSql": "SELECT response_status_code::String, * EXCEPT (response_status_code, unknown)\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nORDER BY timestamp DESC\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Raw Logs; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}