{
 "title": "Fastly Composite Dashboard for Hydrolix",
 "description": "A collection of Grafana panels for monitoring Fastly CDN logs",
 "time": { "from": "now-9d", "to": "now" },
 "templating": {
  "list": [
   { "name": "servers", "label": "Origin Host", "query": "SELECT host FROM fastly.xlogs" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Response Code Metrics (Selected Server:  $servers)",
   "type": "table",
   "description": "Success (1xx/2xx), Redirect(3xx), Error(4xx/5xx)",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\ntoStartOfMonth(day) AS month,\nsum(reqtotal) AS total_requests,\nsum(\"1XX/2XX\") AS success_total,\nround((success_total/total_requests)*100, 2) AS success_rate,\nsum(\"3XX\") AS redirect_total,\nround((redirect_total/total_requests)*100, 2) AS redirect_rate,\nsum(\"4XX/5XX\") AS error_total,\nround((error_total/total_requests)*100, 2) AS error_rate\nFROM (\n  SELECT\n  toDate($dateTimeCol) AS day,\n  count(request) AS reqtotal,\n\tcountIf(match(status, '^[12]\\d\\d')) AS \"1XX/2XX\",\n \tcountIf(match(status, '^3\\d\\d')) AS \"3XX\",\n \tcountIf(match(status, '^[45]\\d\\d')) AS \"4XX/5XX\" \n \tFROM $table\n \tWHERE $timeFilter AND host IN ($servers)\n \tGROUP BY day\n \tORDER BY day\n    )\nGROUP BY month\nORDER BY month",
     "rawQuery": "SELECT\ntoStartOfMonth(day) AS month,\nsum(reqtotal) AS total_requests,\nsum(\"1XX/2XX\") AS success_total,\nround((success_total/total_requests)*100, 2) AS success_rate,\nsum(\"3XX\") AS redirect_total,\nround((redirect_total/total_requests)*100, 2) AS redirect_rate,\nsum(\"4XX/5XX\") AS error_total,\nround((error_total/total_requests)*100, 2) AS error_rate\nFROM (\n  SELECT\n  toDate(time_start) AS day,\n  count(request) AS reqtotal,\n\tcountIf(match(status, '^[12]\\d\\d')) AS \"1XX/2XX\",\n \tcountIf(match(status, '^3\\d\\d')) AS \"3XX\",\n \tcountIf(match(status, '^[45]\\d\\d')) AS \"4XX/5XX\" \n \tFROM fastly.xlogs\n \tWHERE time_start >= toDateTime(1616370691) AND host IN ('try.hydrolix.io','docs.hydrolix.io')\n \tGROUP BY day\n \tORDER BY day\n    )\nGROUP BY month\nORDER BY month",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Cache Status Overview (Selected Server:  $servers)",
   "type": "gauge",
   "description": "Based on the Fastly cache_status field.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfMonth(day) AS month,\n    sum(hits) AS hits,\n    sum(miss) AS miss,\n    sum(pass) AS pass,\n    sum(error) AS error,\n    sum(hit_synth) AS hit_synth,\n    sum(hit_stale) AS hit_stale,\n    sum(hitpass) AS hitpass,\n    sum(none) AS none\nFROM \n(\nSELECT\n        toDate($dateTimeCol) AS day,\n        countIf(cache_status = 'HIT') AS hits,\n        countIf(cache_status = 'MISS') AS miss,\n        countIf(cache_status = 'PASS') AS pass,\n        countIf(cache_status = 'ERROR') AS error,\n        countIf(cache_status = 'HIT-SYNTH') AS hit_synth,\n        countIf(cache_status = 'HIT-STALE') AS hit_stale,\n        countIf(cache_status = 'HITPASS') AS hitpass,\n        countIf(cache_status = 'NONE') AS none\n    FROM $table\n    WHERE $timeFilter AND host IN ($servers)\n    GROUP BY day\n    ORDER BY day\n    )\nGROUP BY month\nORDER BY month\n\n",
     "rawQuery": "SELECT\n    toStartOfMonth(day) AS month,\n    sum(hits) AS hits,\n    sum(miss) AS miss,\n    sum(pass) AS pass,\n    sum(error) AS error,\n    sum(hit_synth) AS hit_synth,\n    sum(hit_stale) AS hit_stale,\n    sum(hitpass) AS hitpass,\n    sum(none) AS none\nFROM \n(\nSELECT\n        toDate(time_start) AS day,\n        countIf(cache_status = 'HIT') AS hits,\n        countIf(cache_status = 'MISS') AS miss,\n        countIf(cache_status = 'PASS') AS pass,\n        countIf(cache_status = 'ERROR') AS error,\n        countIf(cache_status = 'HIT-SYNTH') AS hit_synth,\n        countIf(cache_status = 'HIT-STALE') AS hit_stale,\n        countIf(cache_status = 'HITPASS') AS hitpass,\n        countIf(cache_status = 'NONE') AS none\n    FROM fastly.xlogs\n    WHERE time_start >= toDateTime(1608783295) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\n    GROUP BY day\n    ORDER BY day\n    )\nGROUP BY month\nORDER BY month",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Simple Cache Hit Rate (Selected Server:  $servers)",
   "type": "stat",
   "description": "Simple cache hit ratio calculation. Does not take into account edge and peer caches but can easily be modified:   https://www.fastly.com/blog/truth-about-cache-hit-ratios . Only counts HTTP GET requests.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  sum(request = 'GET') AS total_get_requests,\n  sum(cache_status = 'HIT') AS cache_hits,\n  round(100*cache_hits/total_get_requests, 2) AS \"chr_%\"\n  FROM $table\n  WHERE $timeFilter AND host IN ($servers)\n  \n",
     "rawQuery": "SELECT \n  sum(request = 'GET') AS total_get_requests,\n  sum(cache_status = 'HIT') AS cache_hits,\n  round(100*cache_hits/total_get_requests, 2) AS \"chr_%\"\n  FROM fastly.xlogs\n  WHERE time_start >= toDateTime(1616373473) AND host IN ('docs.hydrolix.io','try.hydrolix.io')",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Cache Error Rate (Selected Server:  $servers)",
   "type": "stat",
   "description": "Simple cache error rate calculation based off of total requests (not limited to GETs but can easily be modified).",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfMonth(day) AS month,\n    sum(error) AS error,\n    sum(total) AS sumtotal,\n    round((error/sumtotal)*100, 2) AS error_rate\nFROM (\n  SELECT\n        toDate($dateTimeCol) AS day,\n        count(request) AS total,\n        countIf(cache_status = 'ERROR') AS error\n        FROM $table\n        WHERE $timeFilter AND host IN ($servers)\n        GROUP BY day\n        ORDER BY day\n    )\nGROUP BY month\nORDER BY month\n\n",
     "rawQuery": "SELECT\n    toStartOfMonth(day) AS month,\n    sum(error) AS error,\n    sum(total) AS sumtotal,\n    round((error/sumtotal)*100, 2) AS error_rate\nFROM (\n  SELECT\n        toDate(time_start) AS day,\n        count(request) AS total,\n        countIf(cache_status = 'ERROR') AS error\n        FROM fastly.xlogs\n        WHERE time_start >= toDateTime(1616373454) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\n        GROUP BY day\n        ORDER BY day\n    )\nGROUP BY month\nORDER BY month",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Origin Server Response Time Distribution by Cache Verdict",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  toDate($dateTimeCol) AS day, host, cache_status, \n  (quantileExact(0.50)(time_elapsed)/1000) AS \"50%-tile (ms)\",\n  (quantileExact(0.75)(time_elapsed)/1000) AS \"75%-tile (ms)\",\n  (quantileExact(0.99)(time_elapsed)/1000) AS \"99%-tile (ms)\"\n  FROM $table\n  WHERE $timeFilter AND host IN ($servers)\n  GROUP BY day, host, cache_status \n  ORDER BY day, cache_status\n",
     "rawQuery": "SELECT \n  toDate(time_start) AS day, host, cache_status, \n  (quantileExact(0.50)(time_elapsed)/1000) AS \"50%-tile (ms)\",\n  (quantileExact(0.75)(time_elapsed)/1000) AS \"75%-tile (ms)\",\n  (quantileExact(0.99)(time_elapsed)/1000) AS \"99%-tile (ms)\"\n  FROM fastly.xlogs\n  WHERE time_start >= toDateTime(1616373487) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\n  GROUP BY day, host, cache_status \n  ORDER BY day, cache_status",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "90%-tile Response Times by Origin Server and Cache Status (Selected Server:  $servers)",
   "type": "timeseries",
   "description": "Useful for detecting anomalies and total request time deviations.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries AS t, \n(quantile(0.90)(time_elapsed)/1000) AS latency, \ncache_status\nFROM $table\nWHERE $timeFilter AND host IN ($servers)\nGROUP BY t, cache_status\nORDER BY t\n\n",
     "rawQuery": "SELECT (intDiv(toUInt32(time_start), 120) * 120) * 1000 AS t, \n(quantile(0.90)(time_elapsed)/1000) AS latency, \ncache_status\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616370669) AND host IN ('try.hydrolix.io','docs.hydrolix.io')\nGROUP BY t, cache_status\nORDER BY t",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Fastly Data Center Performance - Average Request Time",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT geo_datacenter AS dc, avg(time_elapsed)/1000 AS avg_request_time_ms, sum(request= 'GET') AS total_requests\nFROM $table\nWHERE $timeFilter\nGROUP BY dc\nORDER BY avg_request_time_ms DESC, total_requests\n",
     "rawQuery": "SELECT geo_datacenter AS dc, avg(time_elapsed)/1000 AS avg_request_time_ms, sum(request= 'GET') AS total_requests\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616373304)\nGROUP BY dc\nORDER BY avg_request_time_ms DESC, total_requests",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Cache Hit Rate (CHR) Over Time (Selected Server:  $servers)",
   "type": "graph",
   "description": "Panel minimal interval set to 5 mins. Adjust as required.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT t, CHR\nFROM\n(\n  SELECT\n    $timeSeries AS t,\n    sum(request = 'GET') AS requests, sum(cache_status = 'HIT') AS hits,\n    round(hits*100/requests, 1) AS CHR\n    FROM $table\n    WHERE $timeFilter AND host IN ($servers)\n    GROUP BY t\n    ORDER BY t\n)\n",
     "rawQuery": "SELECT t, CHR\nFROM\n(\n  SELECT\n    (intDiv(toUInt32(time_start), 300) * 300) * 1000 AS t,\n    sum(request = 'GET') AS requests, sum(cache_status = 'HIT') AS hits,\n    round(hits*100/requests, 1) AS CHR\n    FROM fastly.xlogs\n    WHERE time_start >= toDateTime(1616373532) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\n    GROUP BY t\n    ORDER BY t\n)",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Overall Average Request Time (Selected Server:  $servers)",
   "type": "graph",
   "description": "Average time it took all requests to be completed per unit of time per server. Select desired origin server at top left of dashboard or build into query.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Time (ms)" }
   ],
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n$timeSeries AS t,\navg(time_elapsed)/1000 AS AvgRT /*average time it took all requests to be completed per unit of time unit per server */\nFROM $table\nWHERE $timeFilter AND host IN ($servers)\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n(intDiv(toUInt32(time_start), 120) * 120) * 1000 AS t,\navg(time_elapsed)/1000 AS AvgRT \nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616373544) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Weekly Top 3 Slowest URLs (Selected Server:  $servers)",
   "type": "table",
   "description": "Time-bucketed $dateTimeCol to toStartOfWeek. Adjust LIMIT n BY as required.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT week, (time_elapsed/1000) AS time_elapsed_ms, concat(host, url) AS full_url\nFROM  (\n   SELECT toStartOfWeek($dateTimeCol) AS week, host, url, time_elapsed \n   FROM $table \n   WHERE $timeFilter AND host IN ($servers)\n   GROUP BY week, host, url, time_elapsed \n   LIMIT 3 BY host\n      ) \nGROUP BY week, full_url, time_elapsed_ms \nORDER BY week, time_elapsed_ms DESC\n\n\n",
     "rawQuery": "SELECT week, (time_elapsed/1000) AS time_elapsed_ms, concat(host, url) AS full_url\nFROM  (\n   SELECT toStartOfWeek(time_start) AS week, host, url, time_elapsed \n   FROM fastly.xlogs \n   WHERE time_start >= toDateTime(1616380283) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\n   GROUP BY week, host, url, time_elapsed \n   LIMIT 3 BY host\n      ) \nGROUP BY week, full_url, time_elapsed_ms \nORDER BY week, time_elapsed_ms DESC",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Weekly Top Error Causing URLs by 4XX/5XX HTTP Response Codes",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT toStartOfWeek($dateTimeCol) AS week, status, cache_status, host, url, count() AS req_count\nfrom $table\nWHERE $timeFilter AND match(status, '^[45]\\d\\d') AND  host IN ($servers)\nGROUP BY week, host, url, status, cache_status\nORDER by req_count DESC\nLIMIT 10\n\n\n\n",
     "rawQuery": "SELECT toStartOfWeek(time_start) AS week, status, cache_status, host, url, count() AS req_count\nfrom fastly.xlogs\nWHERE time_start >= toDateTime(1616380334) AND match(status, '^[45]\\d\\d') AND  host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY week, host, url, status, cache_status\nORDER by req_count DESC\nLIMIT 10",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Monthly Top 3 Content Types",
   "type": "stat",
   "description": "Grouped monthly but topK(N)(column) assessment controlled by timeFilter.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\ntoStartOfMonth($dateTimeCol) AS month,\ntopK(3)(content_type) AS ct\nFROM $table \nWHERE $timeFilter AND host IN ($servers)\nGROUP BY month\nORDER BY month\nLIMIT 12\n",
     "rawQuery": "SELECT\ntoStartOfMonth(time_start) AS month,\ntopK(3)(content_type) AS ct\nFROM fastly.xlogs \nWHERE time_start >= toDateTime(1616380367) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY month\nORDER BY month\nLIMIT 12",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Daily Top 3 Requested URL Paths Per Host",
   "type": "table",
   "description": "Increase LIMIT n BY if more days and hosts are desired.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nformatDateTime(toDate($dateTimeCol), '%F') AS day,\nhost, cutQueryString(url) AS urlpath, count() AS requests\nFROM $table\nWHERE $timeFilter\nAND  match(url,'^.*\\.(css$|js$|json$|jpg$|js$|png$|svg$|xml$)') != 1 AND host IN ($servers)\nGROUP BY day, host, urlpath\nORDER BY day, host, requests DESC\nLIMIT 3 BY day, host\nLIMIT 6\n",
     "rawQuery": "SELECT\nformatDateTime(toDate(time_start), '%F') AS day,\nhost, cutQueryString(url) AS urlpath, count() AS requests\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1615948936)\nAND  match(url,'^.*\\.(css$|js$|json$|jpg$|js$|png$|svg$|xml$)') != 1 AND host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY day, host, urlpath\nORDER BY day, host, requests DESC\nLIMIT 3 BY day, host\nLIMIT 6",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Percent TLS Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \nsum(is_tls = '1') AS tls,\nsum(is_tls = '0') AS not_tls,\nround(tls/(tls + not_tls)*100, 2) AS \"%tls\"\nFROM $table\nWHERE $timeFilter and host IN ($servers)\n",
     "rawQuery": "SELECT \nsum(is_tls = '1') AS tls,\nsum(is_tls = '0') AS not_tls,\nround(tls/(tls + not_tls)*100, 2) AS \"%tls\"\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616373940) and host IN ('docs.hydrolix.io','try.hydrolix.io')",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Percent HTTP/2 Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \nsum(is_h2 = '1') AS h2,\nsum(is_h2 = '0') AS not_h2,\nround(h2/(h2 + not_h2)*100, 2) AS \"%h2\"\nFROM $table\nWHERE $timeFilter and host IN ($servers)\n",
     "rawQuery": "SELECT \nsum(is_h2 = '1') AS h2,\nsum(is_h2 = '0') AS not_h2,\nround(h2/(h2 + not_h2)*100, 2) AS \"%h2\"\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616373973) and host IN ('docs.hydrolix.io','try.hydrolix.io')",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Percent IPv6 Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \nsum(is_ipv6 = '1') AS ipv6,\nsum(is_ipv6 = '0') AS not_ipv6,\nround(ipv6/(ipv6 + not_ipv6)*100, 2) AS \"%ipv6\"\nFROM $table\nWHERE $timeFilter and host IN ($servers)\n",
     "rawQuery": "SELECT \nsum(is_ipv6 = '1') AS ipv6,\nsum(is_ipv6 = '0') AS not_ipv6,\nround(ipv6/(ipv6 + not_ipv6)*100, 2) AS \"%ipv6\"\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616373981) and host IN ('docs.hydrolix.io','try.hydrolix.io')",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Average Request Size (Bytes)",
   "type": "stat",
   "description": "All request types. Total includes headers and body.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT t, avg(total)\nFROM\n(\n  SELECT \n  $dateTimeCol AS t,\n  sum(req_header_size) AS rs,\n  sum(req_body_size) AS rb,\n  (rs+rb) AS total\n  FROM $table \n  WHERE $timeFilter AND host IN ($servers)\n  GROUP BY t\n  ORDER by t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, avg(total)\nFROM\n(\n  SELECT \n  time_start AS t,\n  sum(req_header_size) AS rs,\n  sum(req_body_size) AS rb,\n  (rs+rb) AS total\n  FROM fastly.xlogs \n  WHERE time_start >= toDateTime(1616374054) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\n  GROUP BY t\n  ORDER by t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Average Response Size (KB)",
   "type": "stat",
   "description": "All request types. Total includes headers and body.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT t, avg(total)\nFROM\n(\n  SELECT \n  $dateTimeCol as t,\n  (sum(resp_header_size)/1000) AS rs,\n  (sum(resp_body_size)/1000) AS rb,\n  (rs+rb) AS total\n  FROM $table \n  WHERE $timeFilter AND host IN ($servers)\n  GROUP BY t\n  ORDER by t\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, avg(total)\nFROM\n(\n  SELECT \n  time_start as t,\n  (sum(resp_header_size)/1000) AS rs,\n  (sum(resp_body_size)/1000) AS rb,\n  (rs+rb) AS total\n  FROM fastly.xlogs \n  WHERE time_start >= toDateTime(1616374090) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\n  GROUP BY t\n  ORDER by t\n)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Requests by Fastly Data Center (Selected Server: $servers)",
   "type": "grafana-piechart-panel",
   "description": " 1 AS t, /* fake timestamp value */ for proper bucketing. Reference https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/ for more information.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 90 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n1 AS t, \ngeo_datacenter AS dc, \ncount() AS cnt \nFROM $table\nWHERE $timeFilter AND host IN ($servers)\nGROUP BY t, dc\nORDER BY cnt DESC\nLIMIT 10\n",
     "rawQuery": "SELECT\n1 AS t, \ngeo_datacenter AS dc, \ncount() AS cnt \nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616529594) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY t, dc\nORDER BY cnt DESC\nLIMIT 10",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Request Distribution by Origin Host",
   "type": "grafana-piechart-panel",
   "description": "Substitute Hydrolix hosts. Alternatively, the query could be changed to do a simple count() against all hosts and the origin host filter($servers) variable applied as an example.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 90 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  $dateTimeCol as t,     \n  countIf(startsWith(host,'docs')) / count() * 100 as \"docs.hydrolix.io\",\n  countIf(startsWith(host,'try')) / count() * 100 as \"try.hydrolix.io\"\n  FROM $table  \n  WHERE $timeFilter\n  GROUP BY t\n  ORDER BY t ",
     "rawQuery": "SELECT \n  time_start as t,     \n  countIf(startsWith(host,'docs')) / count() * 100 as \"docs.hydrolix.io\",\n  countIf(startsWith(host,'try')) / count() * 100 as \"try.hydrolix.io\"\n  FROM fastly.xlogs  \n  WHERE time_start >= toDateTime(1616503826)\n  GROUP BY t\n  ORDER BY t",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Top Request Referrers (Selected Server: $servers)",
   "type": "grafana-piechart-panel",
   "description": "1 AS t, /* fake timestamp value */ for proper bucketing. Reference https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/ for more information.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 90 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 1 AS t, \nrequest_referer AS rf, \ncount() AS reqs\nFROM $table \nWHERE $timeFilter AND host IN ($servers)\nGROUP BY t, rf\nORDER BY reqs DESC\nLIMIT 10",
     "rawQuery": "SELECT 1 AS t, \nrequest_referer AS rf, \ncount() AS reqs\nFROM fastly.xlogs \nWHERE time_start >= toDateTime(1616529551) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY t, rf\nORDER BY reqs DESC\nLIMIT 10",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Daily Top 10 - Requests by Country (Selected Server: $servers)",
   "type": "graph",
   "description": "Bucketed by day. Limited to Top 10. Time window pinned at 24 hours with 1 mins scrap time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "# of Requests" }
   ],
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoDate($dateTimeCol) AS day, \ngeo_country_code AS country, \nsum(request= 'GET') AS requests\nFROM $table\nWHERE $timeFilter AND host IN ($servers)\nGROUP BY day, country\nORDER BY requests DESC\nLIMIT 10\n\n",
     "rawQuery": "SELECT \ntoDate(time_start) AS day, \ngeo_country_code AS country, \nsum(request= 'GET') AS requests\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616466408) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY day, country\nORDER BY requests DESC\nLIMIT 10",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Daily Top 10 - Requests by Geolocation (Selected Server: $servers)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT toDate($dateTimeCol) as day, \ngeo_city AS city, \ngeo_country_code AS country, \ncount() as count\nFROM $table\nWHERE $timeFilter AND city != '(null)' AND host IN ($servers)\nGROUP BY day, city, country\nORDER BY count DESC\nLIMIT 10\n\n",
     "rawQuery": "SELECT toDate(time_start) as day, \ngeo_city AS city, \ngeo_country_code AS country, \ncount() as count\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1615948872) AND city != '(null)' AND host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY day, city, country\nORDER BY count DESC\nLIMIT 10",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Unique Visitors by Origin Host",
   "type": "graph",
   "description": "Leverages $columns macro. Based on uniq(client_ip).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    host,\n    uniq(client_ip) unique_clients)\nFROM $table\n",
     "rawQuery": "SELECT t, groupArray((host, unique_clients)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time_start), 20) * 20) * 1000 AS t, host, uniq(client_ip) unique_clients FROM fastly.xlogs WHERE time_start >= toDateTime(1616579484) GROUP BY t, host ORDER BY t, host) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Requests by Country (Selected Server: $servers)",
   "type": "graph",
   "description": "Alternative panel for displaying total GET requests by country. Leverages $column macro.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    geo_country_code,\n    sum(request = 'GET') total_req)\nFROM $table\nWHERE host IN ($servers)\n",
     "rawQuery": "SELECT t, groupArray((geo_country_code, total_req)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time_start), 30) * 30) * 1000 AS t, geo_country_code, sum(request = 'GET') total_req FROM fastly.xlogs\nWHERE time_start >= toDateTime(1616558324) AND host IN ('docs.hydrolix.io','try.hydrolix.io') GROUP BY t, geo_country_code ORDER BY t, geo_country_code) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n$dateTimeCol AS t, \nrequest_user_agent AS ua, \ncount() \nFROM $table\nWHERE $timeFilter AND host IN ($servers)\nGROUP BY t, ua\nORDER BY t\n\n",
     "rawQuery": "SELECT\ntime_start AS t, \nrequest_user_agent AS ua, \ncount() \nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1616375827) AND host IN ('docs.hydrolix.io','try.hydrolix.io')\nGROUP BY t, ua\nORDER BY t",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  },
  {
   "title": "Unusual Request Activity",
   "type": "table",
   "description": "Excludes HTTP GET and POST requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {
     "database": "fastly",
     "dateTimeColDataType": "time_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n$dateTimeCol AS t, request, host, url, client_ip, request_user_agent, request_referer\nFROM $table\nWHERE $timeFilter AND (request != 'GET' AND request != 'POST') \nGROUP BY t, request, host, url, client_ip, request_user_agent, request_referer\nORDER BY t\nLIMIT 25\n",
     "rawQuery": "SELECT\ntime_start AS t, request, host, url, client_ip, request_user_agent, request_referer\nFROM fastly.xlogs\nWHERE time_start >= toDateTime(1608783187) AND (request != 'GET' AND request != 'POST') \nGROUP BY t, request, host, url, client_ip, request_user_agent, request_referer\nORDER BY t\nLIMIT 25",
     "round": "0s",
     "table": "xlogs"
    }
   ]
  }
 ]
}