{
 "title": "Cribl Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Log Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM \"cribl_project\".\"cribl_table\" WHERE ( _time >= $__fromTime AND _time <= $__toTime ) "
    }
   ]
  },
  {
   "title": "Unique Log Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct _raw) FROM \"cribl_project\".\"cribl_table\" WHERE ( _time >= $__fromTime AND _time <= $__toTime ) "
    }
   ]
  },
  {
   "title": "Unique Log %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (count(distinct _raw) / count(*)) FROM \"cribl_project\".\"cribl_table\" WHERE ( _time >= $__fromTime AND _time <= $__toTime ) "
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT _time, _raw FROM \"cribl_project\".\"cribl_table\" WHERE ( _time >= $__fromTime AND _time <= $__toTime ) LIMIT 1000"
    }
   ]
  }
 ]
}